# Generated by Django 5.1.2 on 2024-11-03 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_person_compare_alter_person_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='compare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_set', to='main.car', verbose_name='Автомобили для сравнения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_set', to='main.car', verbose_name='Избранные автомобили'),
        ),
    ]
