# Generated by Django 5.1.2 on 2024-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_compare_alter_person_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='favorite',
        ),
        migrations.AddField(
            model_name='person',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='main.car', verbose_name='Избранные автомобили'),
        ),
    ]
